mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from product.views import (PublisherListView, PublisherDetailView,
                           WriterListView, WriterDetailView)
from .views import IndexHomePagesViews


urlpatterns = [
    path('', IndexHomePagesViews.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('product/', include("product.urls", namespace="product")),
    path('publishers/', PublisherListView.as_view(), name="publisher"),
    path('publishers/<int:pk>/<slug:slug>', PublisherDetailView.as_view(),
         name="publisher-detail"),
    path('region/', include("region.urls", namespace="region")),
    #     path('tutorial/', include("tutorial.urls", namespace="tutorial")),
    path('writer/', WriterListView.as_view(), name="writer"),
    path('writer/<int:pk>/<slug:slug>',
         WriterDetailView.as_view(), name="writer-detail"),
]

product/urls.py
from django.urls import path
from .views import IndexProductView, DetailProductView, SearchResultView


app_name = "product"

urlpatterns = [
    path('', IndexProductView.as_view(), name="index"),
    path('search/', SearchResultView.as_view(), name="search_result"),
    path('books/<int:pk>/<slug:slug>',
         DetailProductView.as_view(), name="product-detail"),
]

region/urls.py
from django.urls import path
from .views import RegionListView

app_name = "region"

urlpatterns = [
    path('', RegionListView.as_view(), name="index"),
]

product/models.py
from django.db import models
from django.utils.text import slugify


# Create your models here.
class AbstractProductModel(models.Model):
    """Class abstrak yang menampung beberapa properti data yang sama dan diwarisi oleh class lainnya."""
    __CATEGORY_DATA = (("writer", "Book Writer"),
                       ("publisher", "Book Publisher"),
                       ("book", "Book"),
                       )

    def get_category_data(self):
        """Method getter untuk mengakses variabel `__CATEGORY_DATA`"""
        return self.__CATEGORY_DATA

    def set_category_data(self, w=False, p=False, b=False):
        """
        Method setter untuk mengubah nilai atribut atau kolom `category_data`.
        Function ini berguna untuk query filter data.
        Parameter `w` artinya writer atau penulis buku.
        Parameter `p` artinya publisher atau penerbit buku.
        Parameter `b` artinya book atau produk buku.
        """
        try:
            if w == True:
                self.category_data = self.get_category_data()[0][0]
                self.save(force_insert=True, force_update=True)

            if p == True:
                self.category_data = self.get_category_data()[1][0]
                self.save(force_insert=True, force_update=True)

            if b == True:
                self.category_data = self.get_category_data()[2][0]
                self.save(force_insert=True, force_update=True)

        except:
            return False

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255, editable=False)
    category_data = models.CharField(max_length=50, blank=True, editable=False)

    class Meta:
        abstract = True


class Writer(AbstractProductModel):
    """Class ini merupakan data model tentang seorang `penulis buku`."""
    name = models.CharField(max_length=100, unique=True)
    full_name = models.CharField(max_length=100, unique=True)
    about = models.TextField(blank=True, null=True)
    images = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.full_name)
        self.set_category_data(w=True)

        super(Writer, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["name"]


class Publisher(AbstractProductModel):
    """Class ini merupakan data model perusahaan `penerbit buku`."""
    name = models.CharField(max_length=100)
    company_name = models.CharField(max_length=100)
    about = models.TextField(blank=True, null=True)
    images = models.CharField(max_length=255, blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.company_name)
        self.set_category_data(p=True)

        super(Publisher, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["name"]


class Book(AbstractProductModel):
    """Class ini merupakan model untuk data `produk buku`"""
    title = models.CharField(max_length=255)
    writer = models.ForeignKey(Writer, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    years = models.IntegerField()
    description = models.TextField()
    cover_book = models.CharField(max_length=255, blank=True)
    price = models.IntegerField(default=0)
    avail_stock = models.IntegerField(default=0)
    isbn = models.CharField(max_length=255, blank=True)
    weight = models.FloatField(default=0.0)
    width = models.FloatField(default=0.0)
    length = models.FloatField(default=0.0)
    pages_count = models.IntegerField(default=0)
    is_discount = models.BooleanField(default=False)
    discount = models.IntegerField(default=0)
    price_discount = models.IntegerField(default=0)

    def is_discounted(self):
        """
        Function setter untuk memeriksa kondisi kolom field `is_discount`. Jika field
        tersebut bernilai True, maka akan mengeksekusi function `price_after_discount`.
        Jika `is_discount` bernilai False, maka fields `discount` dan `price_discount`
        akan di setting kembali menjadi nilai defaultnya.
        """
        if self.is_discount == True:
            self.price_after_discount()

        else:
            self.discount = 0
            self.price_discount = 0

    def price_after_discount(self):
        """
        Jika terdapat diskon, maka harga final produk adalah setelah dikurangi diskon.
        """
        self.price_discount = self.price - (self.price * self.discount / 100)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.set_category_data(b=True)
        self.is_discounted()

        super(Book, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["title"]
        # pass

product/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.views.generic import ListView, DetailView, RedirectView
from typing import Any
from .models import Book, Writer, Publisher


# Create your views here.
class IndexProductView(ListView):
    """
    Class View untuk menampilkan halaman Beranda produk.
    """
    template_name = "product/index.html"
    model = Book
    context_object_name = "Books"
    extra_context = {"page_title": "Produk", "website": "Toko Buku"}

    def get_queryset(self):
        object_list = Book.objects.all()
        return object_list


class DetailProductView(DetailView):
    """
    Class View untuk menampilkan halaman Detail produk yang dipilih (di klik)
    """
    model = Book
    template_name = "product/detail.html"
    context_object_name = "Books"
    extra_context = {}

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.query_pk_and_slug = True
        self.queryset = Book.objects.filter(id=kwargs.get("pk"))

        if request.method == "GET":

            self.extra_context.update({
                "page_title": Book.objects.get(id=kwargs.get("pk")).title,
            })

            print("Siapa user saat ini: {}".format(request.user))

        return super().get(request, self.query_pk_and_slug)


class PublisherListView(ListView):
    """
    Class View untuk menampilkan halaman Beranda penerbit buku.
    """
    model = Publisher
    context_object_name = "publisher"
    extra_context = {"page_title": "Daftar Penerbit", "website": "Toko Buku"}


class PublisherDetailView(DetailView):
    """
    Class View untuk menampilkan halaman Detail penerbit buku yang dipilih (di klik).
    """
    model = Publisher
    template_name = "product/publisher_detail.html"
    context_object_name = "publisher"
    extra_context = {}

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.query_pk_and_slug = True
        self.queryset = Publisher.objects.filter(id=kwargs.get("pk"))

        if request.method == "GET":

            self.extra_context.update({
                "page_title": Publisher.objects.get(id=kwargs.get("pk")).name,
                "related_book": Book.objects.filter(publisher_id=kwargs.get("pk")),
            })

        return super().get(request, *args, **kwargs)


class WriterListView(ListView):
    """
    Class View untuk menampilkan halaman Beranda penulis buku.
    """
    model = Writer
    context_object_name = "writer"
    extra_context = {"page_title": "Daftar Penulis", "website": "Toko Buku"}


class WriterDetailView(DetailView):
    """
    Class View untuk menampilkan halaman Detail penulis buku yang dipilih (di klik).
    """
    model = Writer
    template_name = "product/writer_detail.html"
    context_object_name = "writer"
    extra_context = {}

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.query_pk_and_slug = True
        self.queryset = Writer.objects.filter(id=kwargs.get("pk"))

        if request.method == "GET":

            self.extra_context.update({
                "page_title": Writer.objects.get(id=kwargs.get("pk")).name,
                "related_book": Book.objects.filter(writer_id=kwargs.get("pk")),
            })

        return super().get(request, *args, **kwargs)


class SearchResultView(ListView):
    """
    Class View untuk melakukan pencarian data.
    """
    model = Book
    template_name = "search.html"
    extra_context = {}

    def get_queryset(self) -> QuerySet[Any]:
        query = self.request.GET.get("q")

        object_list = Book.objects.filter(
            Q(title__icontains=query)
        )

        # Update context dengan kata kunci dari pencarian di HTML
        self.extra_context.update({"keyword": query})

        return object_list

    def get(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
        self.queryset = self.get_queryset()
        not_found = len(self.queryset)

        if not_found == 0:
            self.extra_context.update({
                "message": "Tidak ditemukan."
            })

        # # Untuk melihat isi QuerySet melalui terminal/command prompt
        # print("Isi data QuerySet = {}".format(self.queryset))
        # print("Jumlah isi data QuerySet = {}".format(len(self.queryset)))

        return super().get(request, *args, **kwargs)

product/templates/product/detail.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}

<div class="container">
    <p><a href="{% url 'product:index' %}">Kembali</a></p>
    <div class="row">
        <div class="col">
            <img src="{% static 'product/book' %}/{{Books.cover_book}}"
            alt="{{Books.cover_book}}"
            style="width: 50%;">
            <div class="row pt-5">
                <h3 class="pb-3">Rp. {{Books.price|intcomma}}</h3>
                <span>
                    <!-- Button trigger Bootstrap modal -->
                    <a type="button" href="#" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                        Tambah Keranjang
                    </a>
                    <a href="#" class="btn btn-primary">Tambah Wishlist</a>
                    <!-- Button trigger Bootstrap modal -->
                    
                    <!-- Bootstrap modal -->
                    {% include "snippets/modal.html" %}
                    
                    <hr style="width: 70%;">
                    <h4>Informasi lain</h4>
                    <p>Berat: {{Books.weight}} kg</p>
                    <p>Panjang: {{Books.length}} cm</p>
                    <p>Lebar: {{Books.width}} cm</p>
                    <p>ISBN {{Books.isbn}}</p>
                </span>
            </div>
        </div>
        <div class="col" style="padding-left: 0; padding-right: auto;">
            <h1>{{Books.title}}</h1>
            <p>Penulis: <a href="{% url 'writer-detail' pk=Books.writer_id slug=Books.writer.slug %}" style="text-decoration: none;">{{Books.writer}}</a></p>
            <p>Penerbit: <a href="{% url 'publisher-detail' pk=Books.publisher_id slug=Books.publisher.slug %}"
                            style="text-decoration: none;">{{Books.publisher}}</a></p>
            <p>Tahun: {{Books.years}}</p>
            <p class="text-align-justify">{{Books.description | linebreaks}}</p>
        </div>
    </div>
</div>

{% endblock contents %}

product/templates/product/index.html
{% extends "base.html" %}
{% load static %}
{% load humanize %} <!-- `intcomma` untuk memberikan format koma pada harga -->


{% block contents %}
<h1 class="pb-5">Daftar Produk</h1>
<div class="row row-cols-5">
    {% for book in Books %}
        <div class="col pb-2" style="margin-right: 55px;">
            {% if book.is_discount %}
            <div class="card shadow-sm" style="width: 15rem;">
                <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                    <span class="badge text-bg-danger" style="clip: auto;">{{book.discount}}%</span>
                    <img src="{% static 'product/book' %}/{{book.cover_book}}"
                        class="card-img-top"
                        style="width: 100%; max-height: 250px; object-fit: contain;">
                </a>
                <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}"
                        class="text-dark text-decoration-none">
                        <h5 class="card-title pb-1"
                            style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                    </a>
                    <span>
                        Rp.<del>{{book.price|intcomma}}</del> <strong>{{book.price_discount|intcomma}}</strong>
                    </span>
                </div>
            </div>
            {% else %}
            <div class="card shadow-sm" style="width: 15rem;">
                <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                    <span class="badge" style="clip: auto;">None</span>
                    <img src="{% static 'product/book' %}/{{book.cover_book}}"
                        class="card-img-top"
                        style="width: 100%; max-height: 250px; object-fit: contain;">
                </a>
                <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}"
                        class="text-dark text-decoration-none">
                        <h5 class="card-title pb-1"
                            style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                    </a>
                    <span>
                        Rp. {{book.price|intcomma}}
                    </span>
                </div>
            </div>
            {% endif %}
        </div>
    {% endfor %}
    <!-- Navigasi halaman Bootstrap -->
    <div class="container pt-3 pb-5">
        <nav aria-label="Page navigation">
            <ul class="pagination justify-content-center">
                <li class="page-item disabled">
                    <a class="page-link">Previous</a>
                </li>
                <li class="page-item"><a class="page-link" href="{% url 'product:index' %}">1</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'product:index' %}">2</a></li>
                <li class="page-item"><a class="page-link" href="{% url 'product:index' %}">3</a></li>
                <li class="page-item">
                    <a class="page-link" href="{% url 'product:index' %}">Next</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
{% endblock contents %}

product/templates/product/publisher_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<div class="container">
    <p><a href="{% url 'product:index' %}">Kembali</a></p>
    <div class="row">
        <div class="col">
            <img src="{% static 'product/publisher' %}/{{publisher.images}}" style="width: 60%;">
        </div>
        <div class="col" style="padding-left: 0; padding-right: auto;">
            <h1>{{publisher.name}}</h1>
            <p class="text-align-justify">{{publisher.about | linebreaks}}</p>
        </div>
    </div>
    <!-- Daftar buku dari penerbit -->
    <hr>
    <h4 class="pb-3 pt-4">Buku terbitan {{publisher.name}}</h4>
    <div class="container">
        <div class="row row-cols-5">
            {% for book in related_book %}
            <div class="col pb-2" style="margin-right: 55px;">
                {% if book.is_discount %}
                <div class="card shadow-sm" style="width: 15rem;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                        <span class="badge text-bg-danger" style="clip: auto;">{{book.discount}}%</span>
                        <img src="{% static 'product/book' %}/{{book.cover_book}}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                    </a>
                    <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                        <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}" class="text-dark text-decoration-none">
                            <h5 class="card-title pb-1"
                                style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                        </a>
                    </div>
                </div>
                {% else %}
                <div class="card shadow-sm" style="width: 15rem;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                        <span class="badge" style="clip: auto;">None</span>
                        <img src="{% static 'product/book' %}/{{book.cover_book}}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                    </a>
                    <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                        <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}"
                            class="text-dark text-decoration-none">
                            <h5 class="card-title pb-1"
                                style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock contents %}

product/templates/product/publisher_list.html
{% extends "base.html" %}
{% load static %}


{% block contents %}

<div class="row row-cols-5">
    {% for data in object_list %}
    <div class="col pb-4" style="margin-right: 55px;">
        <div class="card" style="width: 15rem;">
            <img src="{% static 'product/publisher' %}/{{data.images}}"
                class="card-img-top"
                style="width: 100%; max-height: 250px; object-fit: contain;">
            <div class="card-body">
                <h6><a class="text-decoration-none text-black" href="{% url 'publisher-detail' pk=data.id slug=data.slug %}">{{data.name}}</a></h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock contents %}

product/templates/product/writer_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block contents %}
<div class="container">
    <p><a href="{% url 'product:index' %}">Kembali</a></p>
    <div class="row">
        <div class="col">
            {% if writer.images %}
                <img src="{% static 'product/writer' %}/{{writer.images}}" style="width: 60%;">
            {% else %}
                <img src="{% static 'icon/profile-icon.jpg' %}" style="width: 60%;">
            {% endif %}
        </div>
        <div class="col" style="padding-left: 0; padding-right: auto;">
            <h1>{{writer.name}}</h1>
            <p class="text-align-justify">{{writer.about | linebreaks}}</p>
        </div>
    </div>
    <!-- Daftar buku dari penulis -->
    <hr>
    <h4 class="pb-3 pt-4">Buku yang ditulis oleh {{writer.name}}</h4>
    <div class="container">
        <div class="row row-cols-5">
            {% for book in related_book %}
            <div class="col pb-2" style="margin-right: 55px;">
                {% if book.is_discount %}
                <div class="card shadow-sm" style="width: 15rem;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                        <span class="badge text-bg-danger" style="clip: auto;">{{book.discount}}%</span>
                        <img src="{% static 'product/book' %}/{{book.cover_book}}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                    </a>
                    <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                        <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}" class="text-dark text-decoration-none">
                            <h5 class="card-title pb-1"
                                style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                        </a>
                    </div>
                </div>
                {% else %}
                <div class="card shadow-sm" style="width: 15rem;">
                    <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}">
                        <span class="badge" style="clip: auto;">None</span>
                        <img src="{% static 'product/book' %}/{{book.cover_book}}"
                            class="card-img-top"
                            style="width: 100%; max-height: 250px; object-fit: contain;">
                    </a>
                    <div class="card-body" style="max-height: 300px; overflow-y: auto;">
                        <a href="{% url 'product:product-detail' pk=book.id slug=book.slug %}"
                            class="text-dark text-decoration-none">
                            <h5 class="card-title pb-1"
                                style="overflow: hidden; white-space: nowrap; text-overflow: ellipsis;">{{book.title}}</h5>
                        </a>
                    </div>
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock contents %}

product/templates/product/writer_list.html
{% extends "base.html" %}
{% load static %}


{% block contents %}

<div class="row row-cols-5">
    {% for data in object_list %}
    <div class="col pb-4" style="margin-right: 55px;">
        <div class="card" style="width: 15rem;">
            <img src="{% static 'product/writer' %}/{{data.images}}"
                class="card-img-top"
                style="width: 100%; max-height: 250px; object-fit: contain;">
            <div class="card-body">
                <h6><a class="text-decoration-none text-black" href="{% url 'writer-detail' pk=data.id slug=data.slug %}">{{data.name}}</a></h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock contents %}