mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from product.views import (PublisherListView, PublisherDetailView,
                           WriterListView, WriterDetailView)
from .views import IndexHomePagesViews


urlpatterns = [
    path('', IndexHomePagesViews.as_view(), name="index"),
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('product/', include("product.urls", namespace="product")),
    path('publishers/', PublisherListView.as_view(), name="publisher"),
    path('publishers/<int:pk>/<slug:slug>', PublisherDetailView.as_view(),
         name="publisher-detail"),
    path('region/', include("region.urls", namespace="region")),
    #     path('tutorial/', include("tutorial.urls", namespace="tutorial")),
    path('writer/', WriterListView.as_view(), name="writer"),
    path('writer/<int:pk>/<slug:slug>',
         WriterDetailView.as_view(), name="writer-detail"),
]

product/urls.py
from django.urls import path
from .views import IndexProductView, DetailProductView, SearchResultView


app_name = "product"

urlpatterns = [
    path('', IndexProductView.as_view(), name="index"),
    path('search/', SearchResultView.as_view(), name="search_result"),
    path('books/<int:pk>/<slug:slug>',
         DetailProductView.as_view(), name="product-detail"),
]

region/urls.py
from django.urls import path
from .views import RegionListView

app_name = "region"

urlpatterns = [
    path('', RegionListView.as_view(), name="index"),
]

templates/snippets/modal.html
<!-- Bootstrap Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            {% if user.is_authenticated %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Buy this book?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Hello, {{user.username}}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            {% else %}
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">You haven't already login!</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <p>Untuk membeli buku ini, Anda perlu <a href="{% url 'login' %}">login</a> dengan akun Anda.</p>
                    <p>Belum punya akun? Silahkan mendaftar akun baru <a href="{% url 'signup' %}">disini</a></p>
                </div>
                <div class="modal-footer">
                    <!-- <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="button" class="btn btn-primary">Save changes</button> -->
                </div>
            {% endif %}
        </div>
    </div>
</div>
<!-- Bootstrap Modal -->

templates/snippets/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Toko Buku</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'product:index' %}">Products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Our Partner
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'writer' %}">Writer</a></li>
                        <li><a class="dropdown-item" href="{% url 'publisher' %}">Publisher</a></li>
                    </ul>
                </li>
            </ul>
            <!-- Kolom pencarian -->
            <form action="{% url 'product:search_result' %}" method="get" class="d-flex" role="search" style="padding-right: 50px;">
                <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            <ul class="navbar-nav mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{user.username}}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'profile' username=user.username pk=user.pk %}">My Profile</a></li>
                        <li><a class="dropdown-item" href="#">Wishlist</a></li>
                        <li><a class="dropdown-item" href="#">Shop Cart</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{% url 'login' %}" class="nav-link">Login</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/snippets/scripts.html
{% load static %}
<script src="{% static 'vendor/bootstrap/bootstrap.bundle.js' %}"></script>
<script src="{% static 'vendor/jquery/jquery.js'  %}"></script>
<script src="{% static 'vendor/popper/popper.js' %}"></script>
<script src="{% static 'js/form-control.js' %}"></script>

templates/snippets/styles.html
{% load static %}
<link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.css'  %}">